name: tests

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.11
          3.8
          3.7
          3.6
    - run: pip3 install tox hatch
    - run: tox
